---

---
- name: Portainer Docker-Slaves
  ansible.builtin.include_tasks: portainer_docker_slaves.yml
  when:
    - hostvars[inventory_hostname].apps.docker.portainer is defined
    - hostvars[inventory_hostname].apps.docker.portainer.type is defined
    - hostvars[inventory_hostname].apps.docker.portainer.type == "docker-slave"

- name: Portainer MASTER
  ansible.builtin.include_tasks: portainer_master.yml
  when:
    - hostvars[inventory_hostname].apps.docker.portainer is defined
    - hostvars[inventory_hostname].apps.docker.portainer.type is defined
    - hostvars[inventory_hostname].apps.docker.portainer.type == "master"
